# Generated by Django 4.2.7 on 2024-01-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0002_alter_author_author_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
